require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Layout/LineLength:
  Max: 130
  Exclude:
    - config/**/*

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false
  
RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude: 
    - spec/*
    - spec/*/*
    - spec/*/*/*
    
RSpec/LetSetup:
  Exclude:
    - spec/system/admin/* 

Lint/MissingSuper:
  Exclude:
    - 'app/policies/*'

RSpec/NamedSubject:
  Exclude:
    - 'spec/policies/*'

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
